### ISSUE TITLE
issue with training/testing partition

### ISSUE THREAD

**Issue by rola93** [robinreni96/Font_Recognition-DeepFont#2]
hey! I've been following your code, great work!

I assume you run all cells in order.

The only mistake I see is that, first, you apply the data augmentation technique, then, you split your data in train and test. This means that you may be adding an example on train set and its augmented version to the test set. This may lead to overestimated performance on your test set. You need to make sure that Train and Test sets are as independent as possible.

The easy fix is, fist split in train test, and then apply augmentation on both datasets.

**Comment by robinreni96** [comment]
Thank you @rola93  for pointing out the error point . Ill fix it and update the repo soon.
